# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ryhui' do
pod 'AFNetworking', '~> 2.5.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'BDKNotifyHUD', '~> 1.1.0'
pod 'EGOTableViewPullRefreshAndLoadMore', '~> 1.0.4'
end

target 'ryhuiTests' do

end

